import { Entypo, MaterialIcons, MaterialCommunityIcons, AntDesign } from 'react-native-vector-icons';

export const iconLibraries = {
  Entypo,
  MaterialIcons,
  MaterialCommunityIcons,
  AntDesign,
};

export const icons = [
  // Art
  { name: "brush", library: "MaterialIcons" },
  { name: "format-paint", library: "MaterialIcons" },
  { name: "palette", library: "MaterialIcons" },
  { name: "collections", library: "MaterialIcons" },
  { name: "colorize", library: "MaterialIcons" },
  { name: "create", library: "MaterialIcons" },
  { name: "draw", library: "MaterialIcons" },
  { name: "wallpaper", library: "MaterialIcons" },

  // Furniture
  { name: "bathtub", library: "MaterialIcons" },
  { name: "chair", library: "MaterialIcons" },
  { name: "bed", library: "MaterialIcons" },
  { name: "blinds", library: "MaterialIcons" },
  { name: "countertops", library: "MaterialIcons" },
  { name: "curtains", library: "MaterialIcons" },
  { name: "deck", library: "MaterialIcons" },
  { name: "door-back", library: "MaterialIcons" },
  { name: "door-sliding", library: "MaterialIcons" },
  { name: "fireplace", library: "MaterialIcons" },
  { name: "fence", library: "MaterialIcons" },
  { name: "desk", library: "MaterialIcons" },
  { name: "foundation", library: "MaterialIcons" },
  { name: "hot-tub", library: "MaterialIcons" },
  { name: "kitchen", library: "MaterialIcons" },
  { name: "light", library: "MaterialIcons" },
  { name: "lightbulb", library: "MaterialIcons" },
  { name: "lightbulb-outline", library: "MaterialIcons" },
  { name: "microwave", library: "MaterialIcons" },
  { name: "outdoor-grill", library: "MaterialIcons" },
  { name: "shelves", library: "MaterialIcons" },
  { name: "shower", library: "MaterialIcons" },
  { name: "table-bar", library: "MaterialIcons" },
  { name: "table-restaurant", library: "MaterialIcons" },
  { name: "weekend", library: "MaterialIcons" },
  { name: "bookshelf", library: "MaterialCommunityIcons" },

  // Tools
  { name: "architecture", library: "MaterialIcons" },
  { name: "auto-fix-high", library: "MaterialIcons" },
  { name: "content-cut", library: "MaterialIcons" },
  { name: "calculate", library: "MaterialIcons" },
  { name: "construction", library: "MaterialIcons" },
  { name: "build", library: "MaterialIcons" },
  { name: "cleaning-services", library: "MaterialIcons" },
  { name: "hardware", library: "MaterialIcons" },
  { name: "home-repair-service", library: "MaterialIcons" },
  { name: "plumbing", library: "MaterialIcons" },
  { name: "straighten", library: "MaterialIcons" },
  { name: "toolbox", library: "MaterialCommunityIcons" },
  { name: "toolbox-outline", library: "MaterialCommunityIcons" },
  { name: "stethoscope", library: "MaterialCommunityIcons" },

  // Household Items
  { name: "anchor", library: "MaterialIcons" },
  { name: "album", library: "MaterialIcons" },
  { name: "alarm", library: "MaterialIcons" },
  { name: "backpack", library: "MaterialIcons" },
  { name: "business", library: "MaterialIcons" },
  { name: "biotech", library: "MaterialIcons" },
  { name: "blender", library: "MaterialIcons" },
  { name: "beach-access", library: "MaterialIcons" },
  { name: "barcode-reader", library: "MaterialIcons" },
  { name: "cable", library: "MaterialIcons" },
  { name: "camera-alt", library: "MaterialIcons" },
  { name: "camera-roll", library: "MaterialIcons" },
  { name: "campaign", library: "MaterialIcons" },
  { name: "catching-pokemon", library: "MaterialIcons" },
  { name: "celebration", library: "MaterialIcons" },
  { name: "checkroom", library: "MaterialIcons" },
  { name: "fire-extinguisher", library: "MaterialIcons" },
  { name: "fire-hydrant-alt", library: "MaterialIcons" },
  { name: "fitness-center", library: "MaterialIcons" },
  { name: "gavel", library: "MaterialIcons" },
  { name: "headphones", library: "MaterialIcons" },
  { name: "headset-mic", library: "MaterialIcons" },
  { name: "ice-skating", library: "MaterialIcons" },
  { name: "key", library: "MaterialIcons" },
  { name: "lock", library: "MaterialIcons" },
  { name: "lock-open", library: "MaterialIcons" },
  { name: "luggage", library: "MaterialIcons" },
  { name: "phishing", library: "MaterialIcons" },
  { name: "point-of-sale", library: "MaterialIcons" },
  { name: "radio", library: "MaterialIcons" },
  { name: "shopping-cart", library: "MaterialIcons" },
  { name: "shopping-bag", library: "MaterialIcons" },
  { name: "shopping-basket", library: "MaterialIcons" },
  { name: "cards-playing-outline", library: "MaterialCommunityIcons" },
  { name: "dice-multiple", library: "MaterialCommunityIcons" },

  // Food and Dining
  { name: "apple", library: "MaterialIcons" },
  { name: "bakery-dining", library: "MaterialIcons" },
  { name: "cake", library: "MaterialIcons" },
  { name: "coffee", library: "MaterialIcons" },
  { name: "coffee-maker", library: "MaterialIcons" },
  { name: "cookie", library: "MaterialIcons" },
  { name: "egg", library: "MaterialIcons" },
  { name: "fastfood", library: "MaterialIcons" },
  { name: "icecream", library: "MaterialIcons" },
  { name: "kebab-dining", library: "MaterialIcons" },
  { name: "dining", library: "MaterialIcons" },
  { name: "dinner-dining", library: "MaterialIcons" },
  { name: "liquor", library: "MaterialIcons" },
  { name: "lunch-dining", library: "MaterialIcons" },
  { name: "ramen-dining", library: "MaterialIcons" },
  { name: "rice-bowl", library: "MaterialIcons" },
  { name: "tapas", library: "MaterialIcons" },
  { name: "takeout-dining", library: "MaterialIcons" },
  { name: "wine-bar", library: "MaterialIcons" },

  // Actions and Symbols
  { name: "call-merge", library: "MaterialIcons" },
  { name: "clean-hands", library: "MaterialIcons" },
  { name: "soap", library: "MaterialIcons" },

  // Weather
  { name: "cloud", library: "MaterialIcons" },
  { name: "cloudy-snowing", library: "MaterialIcons" },
  { name: "ac-unit", library: "MaterialIcons" },
  { name: "nights-stay", library: "MaterialIcons" },
  { name: "sunny", library: "MaterialIcons" },
  { name: "thunderstorm", library: "MaterialIcons" },
  { name: "weather-night", library: "MaterialCommunityIcons" },


  // Symbols
  { name: "360", library: "MaterialIcons" },
  { name: "air", library: "MaterialIcons" },
  { name: "auto-awesome", library: "MaterialIcons" },
  { name: "music-note", library: "MaterialIcons" },
  { name: "attach-money", library: "MaterialIcons" },
  { name: "autorenew", library: "MaterialIcons" },
  { name: "av-timer", library: "MaterialIcons" },
  { name: "back-hand", library: "MaterialIcons" },
  { name: "bedtime", library: "MaterialIcons" },
  { name: "bolt", library: "MaterialIcons" },
  { name: "camera", library: "MaterialIcons" },
  { name: "heart-broken", library: "MaterialIcons" },
  { name: "hive", library: "MaterialIcons" },

  // Office and Organizational
  { name: "all-inbox", library: "MaterialIcons" },
  { name: "archive", library: "MaterialIcons" },
  { name: "area-chart", library: "MaterialIcons" },
  { name: "assessment", library: "MaterialIcons" },
  { name: "assignment", library: "MaterialIcons" },
  { name: "article", library: "MaterialIcons" },
  { name: "aspect-ratio", library: "MaterialIcons" },
  { name: "attachment", library: "MaterialIcons" },
  { name: "balance", library: "MaterialIcons" },
  { name: "badge", library: "MaterialIcons" },
  { name: "calendar-month", library: "MaterialIcons" },
  { name: "card-travel", library: "MaterialIcons" },
  { name: "ballot", library: "MaterialIcons" },
  { name: "content-paste", library: "MaterialIcons" },
  { name: "credit-card", library: "MaterialIcons" },
  { name: "mail", library: "MaterialIcons" },
  { name: "notebook", library: "MaterialCommunityIcons" },
  { name: "address", library: "Entypo" },
  { name: "passport", library: "MaterialCommunityIcons" },

  // Sports and Recreation
  { name: "trophy", library: "MaterialCommunityIcons" },
  { name: "soccer", library: "MaterialCommunityIcons" },
  { name: "basketball", library: "MaterialCommunityIcons" },

  // People and Social
  { name: "assist-walker", library: "MaterialIcons" },
  { name: "blind", library: "MaterialIcons" },
  { name: "directions-run", library: "MaterialIcons" },
  { name: "directions-walk", library: "MaterialIcons" },
  { name: "downhill-skiing", library: "MaterialIcons" },
  { name: "family-restroom", library: "MaterialIcons" },
  { name: "elderly", library: "MaterialIcons" },
  { name: "hiking", library: "MaterialIcons" },
  { name: "self-improvement", library: "MaterialIcons" },
  { name: "skateboarding", library: "MaterialIcons" },
  { name: "sledding", library: "MaterialIcons" },
  { name: "snowboarding", library: "MaterialIcons" },
  { name: "snowshoeing", library: "MaterialIcons" },
  { name: "sports-gymnastics", library: "MaterialIcons" },

  // Vehicles and Transport
  { name: "agriculture", library: "MaterialIcons" },
  { name: "airplanemode-active", library: "MaterialIcons" },
  { name: "airport-shuttle", library: "MaterialIcons" },
  { name: "conveyor-belt", library: "MaterialIcons" },
  { name: "commute", library: "MaterialIcons" },
  { name: "directions-bike", library: "MaterialIcons" },
  { name: "directions-boat", library: "MaterialIcons" },
  { name: "directions-bus", library: "MaterialIcons" },
  { name: "directions-car", library: "MaterialIcons" },
  { name: "directions-railway", library: "MaterialIcons" },
  { name: "directions-subway", library: "MaterialIcons" },
  { name: "forklift", library: "MaterialIcons" },
  { name: "local-shipping", library: "MaterialIcons" },
  { name: "snowmobile", library: "MaterialIcons" },
  { name: "two-wheeler", library: "MaterialIcons" },
  { name: "pedal-bike", library: "MaterialIcons" },

  // Buildings and Architecture
  { name: "apartment", library: "MaterialIcons" },
  { name: "account-balance", library: "MaterialIcons" },
  { name: "bungalow", library: "MaterialIcons" },
  { name: "cabin", library: "MaterialIcons" },
  { name: "business-center", library: "MaterialIcons" },
  { name: "castle", library: "MaterialIcons" },
  { name: "cell-tower", library: "MaterialIcons" },
  { name: "chalet", library: "MaterialIcons" },
  { name: "church", library: "MaterialIcons" },
  { name: "cottage", library: "MaterialIcons" },
  { name: "corporate-fare", library: "MaterialIcons" },
  { name: "festival", library: "MaterialIcons" },
  { name: "flood", library: "MaterialIcons" },
  { name: "factory", library: "MaterialIcons" },
  { name: "fort", library: "MaterialIcons" },
  { name: "holiday-village", library: "MaterialIcons" },
  { name: "home-work", library: "MaterialIcons" },
  { name: "location-city", library: "MaterialIcons" },
  { name: "mosque", library: "MaterialIcons" },
  { name: "store", library: "MaterialIcons" },
  { name: "storefront", library: "MaterialIcons" },
  { name: "synagogue", library: "MaterialIcons" },
  { name: "temple-buddhist", library: "MaterialIcons" },
  { name: "temple-hindu", library: "MaterialIcons" },
  { name: "villa", library: "MaterialIcons" },
  { name: "warehouse", library: "MaterialIcons" },
  { name: "wb-shade", library: "MaterialIcons" },
  { name: "home-modern", library: "MaterialCommunityIcons" },

  // Child-Related
  { name: "baby-changing-station", library: "MaterialIcons" },
  { name: "child-care", library: "MaterialIcons" },
  { name: "child-friendly", library: "MaterialIcons" },
  { name: "crib", library: "MaterialIcons" },
  { name: "stroller", library: "MaterialIcons" },

  // Creatures
  { name: "bug-report", library: "MaterialIcons" },
  { name: "cruelty-free", library: "MaterialIcons" },
  { name: "goat", library: "MaterialIcons" },
  { name: "pest-control-rodent", library: "MaterialIcons" },
  { name: "pets", library: "MaterialIcons" },

  // Music and Entertainment
  { name: "music", library: "Entypo" },
  { name: "guitar-acoustic", library: "MaterialCommunityIcons" },
  { name: "web", library: "MaterialCommunityIcons" },
  { name: "sound-mix", library: "Entypo" },
  { name: "video-camera", library: "Entypo" },

  // Electronics and Devices
  { name: "cellphone", library: "MaterialCommunityIcons" },
  { name: "computer", library: "MaterialIcons" },
  { name: "monitor", library: "MaterialIcons" },
  { name: "mouse", library: "MaterialIcons" },
  { name: "devices", library: "MaterialIcons" },
  { name: "devices-other", library: "MaterialIcons" },
  { name: "device-hub", library: "MaterialIcons" },
  { name: "device-thermostat", library: "MaterialIcons" },
  { name: "lock-smart", library: "MaterialCommunityIcons" },


  // Coding and Technology
  { name: "code", library: "Entypo" },
  { name: "codesquare", library: "AntDesign" },
  { name: "calculator", library: "Entypo" },
  { name: "book-open-page-variant", library: "MaterialCommunityIcons" },
  { name: "terminal", library: "MaterialIcons" },
  { name: "server-network", library: "MaterialCommunityIcons" },

  // Nature and Environment
  { name: "leaf", library: "MaterialCommunityIcons" },
  { name: "compost", library: "MaterialIcons" },
  { name: "solar-panel-large", library: "MaterialCommunityIcons" },

  // Cleanliness and Maintenance
  { name: "broom", library: "MaterialCommunityIcons" },
  { name: "silverware-clean", library: "MaterialCommunityIcons" },
  { name: "barcode", library: "MaterialCommunityIcons" },
  { name: "card-account-details", library: "MaterialCommunityIcons" },

  // Used by the App
  { name: "add", library: "MaterialIcons" },
  { name: "add-circle-outline", library: "MaterialIcons" },
  { name: "add-circle", library: "MaterialIcons" },
  { name: "lightbulb-outline", library: "MaterialCommunityIcons" },
  { name: "home", library: "MaterialIcons" },
  { name: "tools", library: "Entypo" },
  { name: "", library: "" },
];
