import { Entypo, MaterialIcons, MaterialCommunityIcons, AntDesign } from 'react-native-vector-icons';

export const iconLibraries = {
  Entypo,
  MaterialIcons,
  MaterialCommunityIcons,
  AntDesign,
};

export const icons = [
  { name: "360", library: "MaterialIcons", },
  { name: "account-balance", library: "MaterialIcons", },
  { name: "agriculture", library: "MaterialIcons", },
  { name: "air", library: "MaterialIcons", },
  { name: "airplanemode-active", library: "MaterialIcons", },
  { name: "airport-shuttle", library: "MaterialIcons", },
  { name: "alarm", library: "MaterialIcons", },
  { name: "album", library: "MaterialIcons", },
  { name: "all-inbox", library: "MaterialIcons", },
  { name: "anchor", library: "MaterialIcons", },
  { name: "apartment", library: "MaterialIcons", },
  { name: "apple", library: "MaterialIcons", },
  { name: "architecture", library: "MaterialIcons", },
  { name: "archive", library: "MaterialIcons", },
  { name: "area-chart", library: "MaterialIcons", },
  { name: "article", library: "MaterialIcons", },
  { name: "aspect-ratio", library: "MaterialIcons", },
  { name: "assessment", library: "MaterialIcons", },
  { name: "assignment", library: "MaterialIcons", },
  { name: "assist-walker", library: "MaterialIcons", },
  { name: "auto-awesome", library: "MaterialIcons", },
  { name: "audiotrack", library: "MaterialIcons", },
  { name: "attachment", library: "MaterialIcons", },
  { name: "attach-money", library: "MaterialIcons", },
  { name: "assistant-photo", library: "MaterialIcons", },
  { name: "auto-fix-high", library: "MaterialIcons", },
  { name: "auto-stories", library: "MaterialIcons", },
  { name: "autorenew", library: "MaterialIcons", },
  { name: "av-timer", library: "MaterialIcons", },
  { name: "baby-changing-station", library: "MaterialIcons", },
  { name: "back-hand", library: "MaterialIcons", },
  { name: "backpack", library: "MaterialIcons", },
  { name: "badge", library: "MaterialIcons", },
  { name: "bakery-dining", library: "MaterialIcons", },
  { name: "balance", library: "MaterialIcons", },
  { name: "ballot", library: "MaterialIcons", },
  { name: "format-paint", library: "MaterialIcons", },
  { name: "home-modern", library: "MaterialCommunityIcons", },
  { name: "bike", library: "MaterialCommunityIcons" },
  { name: "flower-tulip", library: "MaterialCommunityIcons" },
  { name: "scissors-cutting", library: "MaterialCommunityIcons" },
  { name: "leaf", library: "MaterialCommunityIcons" },
  { name: "solar-panel-large", library: "MaterialCommunityIcons" },
  { name: "codesquare", library: "AntDesign" },
  { name: "music", library: "Entypo" },
  { name: "wrench", library: "MaterialCommunityIcons" },
  { name: "brush", library: "MaterialCommunityIcons" },
  { name: "calculator", library: "Entypo" },
  { name: "book-open-page-variant", library: "MaterialCommunityIcons" },
  { name: "guitar-acoustic", library: "MaterialCommunityIcons" },
  { name: "code", library: "Entypo" },
  { name: "mobile1", library: "AntDesign" },
  { name: "calculator", library: "MaterialCommunityIcons" },
  { name: "book-open-page-variant", library: "MaterialCommunityIcons" },
  { name: "guitar-acoustic", library: "MaterialCommunityIcons" },
  { name: "run", library: "MaterialCommunityIcons" },
  { name: "yoga", library: "MaterialCommunityIcons" },
  { name: "food-fork-drink", library: "MaterialCommunityIcons" },
  { name: "camera", library: "Entypo" },
  { name: "code-tags", library: "MaterialCommunityIcons" },
  { name: "toolbox", library: "MaterialCommunityIcons" },
  { name: "cards-playing-outline", library: "MaterialCommunityIcons" },
  { name: "apps", library: "MaterialCommunityIcons" },
  { name: "mobile1", library: "AntDesign" },
  { name: "coffee-maker", library: "MaterialCommunityIcons" },
  { name: "web", library: "MaterialCommunityIcons" },
  { name: "dice-multiple", library: "MaterialCommunityIcons" },
  { name: "cellphone", library: "MaterialCommunityIcons" },
  { name: "coffee", library: "MaterialCommunityIcons" },
  { name: "codesquare", library: "AntDesign", },
  { name: "", library: "", },
  { name: "add-circle-outline", library: "MaterialIcons", },
  { name: "add", library: "MaterialIcons", },
  { name: "add-circle", library: "MaterialIcons", },
  { name: "lightbulb-outline", library: "MaterialCommunityIcons", },
  { name: "home", library: "MaterialIcons", },
  { name: "tools", library: "Entypo", },
];